export const defaultGravityConstant = 0.01
export const mouseMoveSensitivity = Math.PI / 800  // radius every 100px
export const mouseScrollSensitivity = 10  // pixel every pixel
export const baiPathPointNum = 20
export const defaultViewPointDistanceToWindow = 800
export const initialViewPointPitch = Math.PI / 4
export const initialViewPointYaw = 0
export const initialViewPointRadius = 4000
export const minObjRadius = 3000
export const maxObjRadius = 8000
export const tanVelocityFromRadius = 0.5
export const minSpeed = 10
export const minRotationAngularSpeed = 0
export const maxRotationAngularSpeed = 0.01
export const imgSize = 800
